name: Generate Snakee Animation

on:
  schedule:
    - cron: "0 0 1 1 *"  
    - cron: "0 0 1 7 *"  

  workflow_dispatch:  

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snakee
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snakee.svg  

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist/snakee.svg
          git commit -m "Updated snakee animation" || echo "No changes to commit"
          git push
